# Generated by Django 6.0.2 on 2026-02-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilteredEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('date_received', models.DateTimeField()),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
    ]
